name: hcblk

services:
  server:
    tty: true
    build:
      context: .
      args:
        PORT: 8080
    ports:
      - 3000:8080
    volumes:
      - logs:/var/log/hcblk/
      - db:/app/assets/db/
      - listings:/app/assets/dist/listings/

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/hcblk/
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/hcblk/db/
  listings:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/hcblk/listings/

