name: hcblk

services:
  server:
    tty: true
    build:
      context: .
      args:
        PORT: 8080
    ports:
      - 3000:8080
    volumes:
      - /var/log/hcblk/:/var/log/hcblk/:rw
      - /var/lib/hcblk/assets/:/app/assets/:rw

